version: "3.8"

services: 
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - '8080:80'
    volumes: 
      - .:/data
      - '/node_modules/data'
    depends_on: 
      - mysql_server
  
  mysql_server:
    image: mysql:8.0
    environment:
   
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: test
      MYSQL_PASSWORD: 
    